/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyContactPersonResponse } from './CompanyContactPersonResponse';
import {
  CompanyContactPersonResponseFromJSON,
  CompanyContactPersonResponseFromJSONTyped,
  CompanyContactPersonResponseToJSON,
  CompanyContactPersonResponseToJSONTyped,
} from './CompanyContactPersonResponse';

/**
 *
 * @export
 * @interface CompanyResponse
 */
export interface CompanyResponse {
  /**
   *
   * @type {string}
   * @memberof CompanyResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof CompanyResponse
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof CompanyResponse
   */
  address?: string;
  /**
   *
   * @type {CompanyContactPersonResponse}
   * @memberof CompanyResponse
   */
  contactPerson?: CompanyContactPersonResponse;
}

/**
 * Check if a given object implements the CompanyResponse interface.
 */
export function instanceOfCompanyResponse(value: object): value is CompanyResponse {
  return true;
}

export function CompanyResponseFromJSON(json: any): CompanyResponse {
  return CompanyResponseFromJSONTyped(json, false);
}

export function CompanyResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanyResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    address: json['address'] == null ? undefined : json['address'],
    contactPerson:
      json['contactPerson'] == null
        ? undefined
        : CompanyContactPersonResponseFromJSON(json['contactPerson']),
  };
}

export function CompanyResponseToJSON(json: any): CompanyResponse {
  return CompanyResponseToJSONTyped(json, false);
}

export function CompanyResponseToJSONTyped(
  value?: CompanyResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    address: value['address'],
    contactPerson: CompanyContactPersonResponseToJSON(value['contactPerson']),
  };
}
