/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CompanyCreateRequest
 */
export interface CompanyCreateRequest {
  /**
   *
   * @type {string}
   * @memberof CompanyCreateRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof CompanyCreateRequest
   */
  address?: string;
}

/**
 * Check if a given object implements the CompanyCreateRequest interface.
 */
export function instanceOfCompanyCreateRequest(value: object): value is CompanyCreateRequest {
  return true;
}

export function CompanyCreateRequestFromJSON(json: any): CompanyCreateRequest {
  return CompanyCreateRequestFromJSONTyped(json, false);
}

export function CompanyCreateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanyCreateRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    address: json['address'] == null ? undefined : json['address'],
  };
}

export function CompanyCreateRequestToJSON(json: any): CompanyCreateRequest {
  return CompanyCreateRequestToJSONTyped(json, false);
}

export function CompanyCreateRequestToJSONTyped(
  value?: CompanyCreateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    address: value['address'],
  };
}
