/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CompanyContactPersonResponse
 */
export interface CompanyContactPersonResponse {
  /**
   *
   * @type {string}
   * @memberof CompanyContactPersonResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof CompanyContactPersonResponse
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof CompanyContactPersonResponse
   */
  number?: string;
  /**
   *
   * @type {string}
   * @memberof CompanyContactPersonResponse
   */
  email?: string;
}

/**
 * Check if a given object implements the CompanyContactPersonResponse interface.
 */
export function instanceOfCompanyContactPersonResponse(
  value: object,
): value is CompanyContactPersonResponse {
  return true;
}

export function CompanyContactPersonResponseFromJSON(json: any): CompanyContactPersonResponse {
  return CompanyContactPersonResponseFromJSONTyped(json, false);
}

export function CompanyContactPersonResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanyContactPersonResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    number: json['number'] == null ? undefined : json['number'],
    email: json['email'] == null ? undefined : json['email'],
  };
}

export function CompanyContactPersonResponseToJSON(json: any): CompanyContactPersonResponse {
  return CompanyContactPersonResponseToJSONTyped(json, false);
}

export function CompanyContactPersonResponseToJSONTyped(
  value?: CompanyContactPersonResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    number: value['number'],
    email: value['email'],
  };
}
