/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompanyResponse } from './CompanyResponse';
import {
  CompanyResponseFromJSON,
  CompanyResponseFromJSONTyped,
  CompanyResponseToJSON,
  CompanyResponseToJSONTyped,
} from './CompanyResponse';
import type { PaginationResponse } from './PaginationResponse';
import {
  PaginationResponseFromJSON,
  PaginationResponseFromJSONTyped,
  PaginationResponseToJSON,
  PaginationResponseToJSONTyped,
} from './PaginationResponse';

/**
 *
 * @export
 * @interface CompaniesResponse
 */
export interface CompaniesResponse {
  /**
   *
   * @type {Array<CompanyResponse>}
   * @memberof CompaniesResponse
   */
  data?: Array<CompanyResponse>;
  /**
   *
   * @type {PaginationResponse}
   * @memberof CompaniesResponse
   */
  pagination?: PaginationResponse;
}

/**
 * Check if a given object implements the CompaniesResponse interface.
 */
export function instanceOfCompaniesResponse(value: object): value is CompaniesResponse {
  return true;
}

export function CompaniesResponseFromJSON(json: any): CompaniesResponse {
  return CompaniesResponseFromJSONTyped(json, false);
}

export function CompaniesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompaniesResponse {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null ? undefined : (json['data'] as Array<any>).map(CompanyResponseFromJSON),
    pagination:
      json['pagination'] == null ? undefined : PaginationResponseFromJSON(json['pagination']),
  };
}

export function CompaniesResponseToJSON(json: any): CompaniesResponse {
  return CompaniesResponseToJSONTyped(json, false);
}

export function CompaniesResponseToJSONTyped(
  value?: CompaniesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null ? undefined : (value['data'] as Array<any>).map(CompanyResponseToJSON),
    pagination: PaginationResponseToJSON(value['pagination']),
  };
}
