/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CompanyUpdateRequest
 */
export interface CompanyUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof CompanyUpdateRequest
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof CompanyUpdateRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof CompanyUpdateRequest
   */
  profileId?: string;
  /**
   *
   * @type {string}
   * @memberof CompanyUpdateRequest
   */
  address?: string;
}

/**
 * Check if a given object implements the CompanyUpdateRequest interface.
 */
export function instanceOfCompanyUpdateRequest(value: object): value is CompanyUpdateRequest {
  return true;
}

export function CompanyUpdateRequestFromJSON(json: any): CompanyUpdateRequest {
  return CompanyUpdateRequestFromJSONTyped(json, false);
}

export function CompanyUpdateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanyUpdateRequest {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    profileId: json['profileId'] == null ? undefined : json['profileId'],
    address: json['address'] == null ? undefined : json['address'],
  };
}

export function CompanyUpdateRequestToJSON(json: any): CompanyUpdateRequest {
  return CompanyUpdateRequestToJSONTyped(json, false);
}

export function CompanyUpdateRequestToJSONTyped(
  value?: CompanyUpdateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    profileId: value['profileId'],
    address: value['address'],
  };
}
