/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ErrorMessageMeta
 */
export interface ErrorMessageMeta {
  /**
   *
   * @type {string}
   * @memberof ErrorMessageMeta
   */
  requestUri?: string;
  /**
   *
   * @type {string}
   * @memberof ErrorMessageMeta
   */
  queryString?: string;
  /**
   *
   * @type {string}
   * @memberof ErrorMessageMeta
   */
  exception?: string;
}

/**
 * Check if a given object implements the ErrorMessageMeta interface.
 */
export function instanceOfErrorMessageMeta(value: object): value is ErrorMessageMeta {
  return true;
}

export function ErrorMessageMetaFromJSON(json: any): ErrorMessageMeta {
  return ErrorMessageMetaFromJSONTyped(json, false);
}

export function ErrorMessageMetaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorMessageMeta {
  if (json == null) {
    return json;
  }
  return {
    requestUri: json['requestUri'] == null ? undefined : json['requestUri'],
    queryString: json['queryString'] == null ? undefined : json['queryString'],
    exception: json['exception'] == null ? undefined : json['exception'],
  };
}

export function ErrorMessageMetaToJSON(json: any): ErrorMessageMeta {
  return ErrorMessageMetaToJSONTyped(json, false);
}

export function ErrorMessageMetaToJSONTyped(
  value?: ErrorMessageMeta | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    requestUri: value['requestUri'],
    queryString: value['queryString'],
    exception: value['exception'],
  };
}
