/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessageEntry } from './ErrorMessageEntry';
import {
  ErrorMessageEntryFromJSON,
  ErrorMessageEntryFromJSONTyped,
  ErrorMessageEntryToJSON,
  ErrorMessageEntryToJSONTyped,
} from './ErrorMessageEntry';

/**
 *
 * @export
 * @interface ErrorMessageBody
 */
export interface ErrorMessageBody {
  /**
   *
   * @type {Array<ErrorMessageEntry>}
   * @memberof ErrorMessageBody
   */
  errors?: Array<ErrorMessageEntry>;
}

/**
 * Check if a given object implements the ErrorMessageBody interface.
 */
export function instanceOfErrorMessageBody(value: object): value is ErrorMessageBody {
  return true;
}

export function ErrorMessageBodyFromJSON(json: any): ErrorMessageBody {
  return ErrorMessageBodyFromJSONTyped(json, false);
}

export function ErrorMessageBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorMessageBody {
  if (json == null) {
    return json;
  }
  return {
    errors:
      json['errors'] == null
        ? undefined
        : (json['errors'] as Array<any>).map(ErrorMessageEntryFromJSON),
  };
}

export function ErrorMessageBodyToJSON(json: any): ErrorMessageBody {
  return ErrorMessageBodyToJSONTyped(json, false);
}

export function ErrorMessageBodyToJSONTyped(
  value?: ErrorMessageBody | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    errors:
      value['errors'] == null
        ? undefined
        : (value['errors'] as Array<any>).map(ErrorMessageEntryToJSON),
  };
}
