/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessageMeta } from './ErrorMessageMeta';
import {
  ErrorMessageMetaFromJSON,
  ErrorMessageMetaFromJSONTyped,
  ErrorMessageMetaToJSON,
  ErrorMessageMetaToJSONTyped,
} from './ErrorMessageMeta';

/**
 *
 * @export
 * @interface ErrorMessageEntry
 */
export interface ErrorMessageEntry {
  /**
   *
   * @type {number}
   * @memberof ErrorMessageEntry
   */
  status?: number;
  /**
   *
   * @type {string}
   * @memberof ErrorMessageEntry
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof ErrorMessageEntry
   */
  detail?: string;
  /**
   *
   * @type {string}
   * @memberof ErrorMessageEntry
   */
  cause?: string;
  /**
   *
   * @type {ErrorMessageMeta}
   * @memberof ErrorMessageEntry
   */
  meta?: ErrorMessageMeta;
}

/**
 * Check if a given object implements the ErrorMessageEntry interface.
 */
export function instanceOfErrorMessageEntry(value: object): value is ErrorMessageEntry {
  return true;
}

export function ErrorMessageEntryFromJSON(json: any): ErrorMessageEntry {
  return ErrorMessageEntryFromJSONTyped(json, false);
}

export function ErrorMessageEntryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorMessageEntry {
  if (json == null) {
    return json;
  }
  return {
    status: json['status'] == null ? undefined : json['status'],
    title: json['title'] == null ? undefined : json['title'],
    detail: json['detail'] == null ? undefined : json['detail'],
    cause: json['cause'] == null ? undefined : json['cause'],
    meta: json['meta'] == null ? undefined : ErrorMessageMetaFromJSON(json['meta']),
  };
}

export function ErrorMessageEntryToJSON(json: any): ErrorMessageEntry {
  return ErrorMessageEntryToJSONTyped(json, false);
}

export function ErrorMessageEntryToJSONTyped(
  value?: ErrorMessageEntry | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value['status'],
    title: value['title'],
    detail: value['detail'],
    cause: value['cause'],
    meta: ErrorMessageMetaToJSON(value['meta']),
  };
}
