/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PaginationResponse
 */
export interface PaginationResponse {
  /**
   *
   * @type {number}
   * @memberof PaginationResponse
   */
  totalRecords?: number;
  /**
   *
   * @type {number}
   * @memberof PaginationResponse
   */
  totalPages?: number;
  /**
   *
   * @type {number}
   * @memberof PaginationResponse
   */
  previousPage?: number;
  /**
   *
   * @type {number}
   * @memberof PaginationResponse
   */
  currentPage?: number;
  /**
   *
   * @type {number}
   * @memberof PaginationResponse
   */
  nextPage?: number;
}

/**
 * Check if a given object implements the PaginationResponse interface.
 */
export function instanceOfPaginationResponse(value: object): value is PaginationResponse {
  return true;
}

export function PaginationResponseFromJSON(json: any): PaginationResponse {
  return PaginationResponseFromJSONTyped(json, false);
}

export function PaginationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaginationResponse {
  if (json == null) {
    return json;
  }
  return {
    totalRecords: json['totalRecords'] == null ? undefined : json['totalRecords'],
    totalPages: json['totalPages'] == null ? undefined : json['totalPages'],
    previousPage: json['previousPage'] == null ? undefined : json['previousPage'],
    currentPage: json['currentPage'] == null ? undefined : json['currentPage'],
    nextPage: json['nextPage'] == null ? undefined : json['nextPage'],
  };
}

export function PaginationResponseToJSON(json: any): PaginationResponse {
  return PaginationResponseToJSONTyped(json, false);
}

export function PaginationResponseToJSONTyped(
  value?: PaginationResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    totalRecords: value['totalRecords'],
    totalPages: value['totalPages'],
    previousPage: value['previousPage'],
    currentPage: value['currentPage'],
    nextPage: value['nextPage'],
  };
}
