/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ProfileUpdateRequest
 */
export interface ProfileUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof ProfileUpdateRequest
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileUpdateRequest
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileUpdateRequest
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileUpdateRequest
   */
  number?: string;
}

/**
 * Check if a given object implements the ProfileUpdateRequest interface.
 */
export function instanceOfProfileUpdateRequest(value: object): value is ProfileUpdateRequest {
  return true;
}

export function ProfileUpdateRequestFromJSON(json: any): ProfileUpdateRequest {
  return ProfileUpdateRequestFromJSONTyped(json, false);
}

export function ProfileUpdateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProfileUpdateRequest {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    firstName: json['firstName'] == null ? undefined : json['firstName'],
    lastName: json['lastName'] == null ? undefined : json['lastName'],
    number: json['number'] == null ? undefined : json['number'],
  };
}

export function ProfileUpdateRequestToJSON(json: any): ProfileUpdateRequest {
  return ProfileUpdateRequestToJSONTyped(json, false);
}

export function ProfileUpdateRequestToJSONTyped(
  value?: ProfileUpdateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    firstName: value['firstName'],
    lastName: value['lastName'],
    number: value['number'],
  };
}
