/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ProfileCreateRequest
 */
export interface ProfileCreateRequest {
  /**
   *
   * @type {string}
   * @memberof ProfileCreateRequest
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileCreateRequest
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileCreateRequest
   */
  number?: string;
}

/**
 * Check if a given object implements the ProfileCreateRequest interface.
 */
export function instanceOfProfileCreateRequest(value: object): value is ProfileCreateRequest {
  return true;
}

export function ProfileCreateRequestFromJSON(json: any): ProfileCreateRequest {
  return ProfileCreateRequestFromJSONTyped(json, false);
}

export function ProfileCreateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProfileCreateRequest {
  if (json == null) {
    return json;
  }
  return {
    firstName: json['firstName'] == null ? undefined : json['firstName'],
    lastName: json['lastName'] == null ? undefined : json['lastName'],
    number: json['number'] == null ? undefined : json['number'],
  };
}

export function ProfileCreateRequestToJSON(json: any): ProfileCreateRequest {
  return ProfileCreateRequestToJSONTyped(json, false);
}

export function ProfileCreateRequestToJSONTyped(
  value?: ProfileCreateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    firstName: value['firstName'],
    lastName: value['lastName'],
    number: value['number'],
  };
}
