/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ProfileResponse
 */
export interface ProfileResponse {
  /**
   *
   * @type {string}
   * @memberof ProfileResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileResponse
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileResponse
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileResponse
   */
  number?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileResponse
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof ProfileResponse
   */
  email?: string;
}

/**
 * Check if a given object implements the ProfileResponse interface.
 */
export function instanceOfProfileResponse(value: object): value is ProfileResponse {
  return true;
}

export function ProfileResponseFromJSON(json: any): ProfileResponse {
  return ProfileResponseFromJSONTyped(json, false);
}

export function ProfileResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProfileResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    firstName: json['firstName'] == null ? undefined : json['firstName'],
    lastName: json['lastName'] == null ? undefined : json['lastName'],
    number: json['number'] == null ? undefined : json['number'],
    type: json['type'] == null ? undefined : json['type'],
    email: json['email'] == null ? undefined : json['email'],
  };
}

export function ProfileResponseToJSON(json: any): ProfileResponse {
  return ProfileResponseToJSONTyped(json, false);
}

export function ProfileResponseToJSONTyped(
  value?: ProfileResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    firstName: value['firstName'],
    lastName: value['lastName'],
    number: value['number'],
    type: value['type'],
    email: value['email'],
  };
}
