/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResponse } from './PaginationResponse';
import {
  PaginationResponseFromJSON,
  PaginationResponseFromJSONTyped,
  PaginationResponseToJSON,
  PaginationResponseToJSONTyped,
} from './PaginationResponse';
import type { ProfileResponse } from './ProfileResponse';
import {
  ProfileResponseFromJSON,
  ProfileResponseFromJSONTyped,
  ProfileResponseToJSON,
  ProfileResponseToJSONTyped,
} from './ProfileResponse';

/**
 *
 * @export
 * @interface ProfilesResponse
 */
export interface ProfilesResponse {
  /**
   *
   * @type {Array<ProfileResponse>}
   * @memberof ProfilesResponse
   */
  data?: Array<ProfileResponse>;
  /**
   *
   * @type {PaginationResponse}
   * @memberof ProfilesResponse
   */
  pagination?: PaginationResponse;
}

/**
 * Check if a given object implements the ProfilesResponse interface.
 */
export function instanceOfProfilesResponse(value: object): value is ProfilesResponse {
  return true;
}

export function ProfilesResponseFromJSON(json: any): ProfilesResponse {
  return ProfilesResponseFromJSONTyped(json, false);
}

export function ProfilesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProfilesResponse {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null ? undefined : (json['data'] as Array<any>).map(ProfileResponseFromJSON),
    pagination:
      json['pagination'] == null ? undefined : PaginationResponseFromJSON(json['pagination']),
  };
}

export function ProfilesResponseToJSON(json: any): ProfilesResponse {
  return ProfilesResponseToJSONTyped(json, false);
}

export function ProfilesResponseToJSONTyped(
  value?: ProfilesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null ? undefined : (value['data'] as Array<any>).map(ProfileResponseToJSON),
    pagination: PaginationResponseToJSON(value['pagination']),
  };
}
