/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type CompaniesResponse,
  CompaniesResponseFromJSON,
  CompaniesResponseToJSON,
} from '../models/CompaniesResponse';
import {
  type CompanyCreateRequest,
  CompanyCreateRequestFromJSON,
  CompanyCreateRequestToJSON,
} from '../models/CompanyCreateRequest';
import {
  type CompanyResponse,
  CompanyResponseFromJSON,
  CompanyResponseToJSON,
} from '../models/CompanyResponse';
import {
  type CompanyUpdateRequest,
  CompanyUpdateRequestFromJSON,
  CompanyUpdateRequestToJSON,
} from '../models/CompanyUpdateRequest';
import {
  type ErrorMessageBody,
  ErrorMessageBodyFromJSON,
  ErrorMessageBodyToJSON,
} from '../models/ErrorMessageBody';

export interface CreateCompanyRequest {
  companyCreateRequest?: CompanyCreateRequest;
}

export interface DeleteCompanyRequest {
  id: string;
}

export interface GetCompaniesRequest {
  page?: number;
  pageSize?: number;
}

export interface GetCompanyRequest {
  id: string;
}

export interface UpdateCompanyRequest {
  id: string;
  companyUpdateRequest?: CompanyUpdateRequest;
}

/**
 *
 */
export class CompanyApi extends runtime.BaseAPI {
  /**
   * Creates request options for createCompany without sending the request
   */
  async createCompanyRequestOpts(
    requestParameters: CreateCompanyRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken('oauth', [
        'company_write',
      ]);
    }

    let urlPath = `/api/v1/companies`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: CompanyCreateRequestToJSON(requestParameters['companyCreateRequest']),
    };
  }

  /**
   * Create a new company
   * Create a new company
   */
  async createCompanyRaw(
    requestParameters: CreateCompanyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CompanyResponse>> {
    const requestOptions = await this.createCompanyRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => CompanyResponseFromJSON(jsonValue));
  }

  /**
   * Create a new company
   * Create a new company
   */
  async createCompany(
    requestParameters: CreateCompanyRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CompanyResponse> {
    const response = await this.createCompanyRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for deleteCompany without sending the request
   */
  async deleteCompanyRequestOpts(
    requestParameters: DeleteCompanyRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteCompany().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken('oauth', [
        'company_write',
      ]);
    }

    let urlPath = `/api/v1/companies/{id}`;
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Delete a company
   * Delete a company
   */
  async deleteCompanyRaw(
    requestParameters: DeleteCompanyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteCompanyRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a company
   * Delete a company
   */
  async deleteCompany(
    requestParameters: DeleteCompanyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteCompanyRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for getCompanies without sending the request
   */
  async getCompaniesRequestOpts(
    requestParameters: GetCompaniesRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['pageSize'] = requestParameters['pageSize'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken('oauth', [
        'company_read',
      ]);
    }

    let urlPath = `/api/v1/companies`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Retrieve all companies
   * Retrieve all companies
   */
  async getCompaniesRaw(
    requestParameters: GetCompaniesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CompaniesResponse>> {
    const requestOptions = await this.getCompaniesRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CompaniesResponseFromJSON(jsonValue),
    );
  }

  /**
   * Retrieve all companies
   * Retrieve all companies
   */
  async getCompanies(
    requestParameters: GetCompaniesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CompaniesResponse> {
    const response = await this.getCompaniesRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getCompany without sending the request
   */
  async getCompanyRequestOpts(requestParameters: GetCompanyRequest): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getCompany().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken('oauth', [
        'company_read',
      ]);
    }

    let urlPath = `/api/v1/companies/{id}`;
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Retrieve a single company by id
   * Retrieve a company by id
   */
  async getCompanyRaw(
    requestParameters: GetCompanyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CompanyResponse>> {
    const requestOptions = await this.getCompanyRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => CompanyResponseFromJSON(jsonValue));
  }

  /**
   * Retrieve a single company by id
   * Retrieve a company by id
   */
  async getCompany(
    requestParameters: GetCompanyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CompanyResponse> {
    const response = await this.getCompanyRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateCompany without sending the request
   */
  async updateCompanyRequestOpts(
    requestParameters: UpdateCompanyRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updateCompany().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken('oauth', [
        'company_write',
      ]);
    }

    let urlPath = `/api/v1/companies/{id}`;
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: CompanyUpdateRequestToJSON(requestParameters['companyUpdateRequest']),
    };
  }

  /**
   * Update a company
   * Update a company
   */
  async updateCompanyRaw(
    requestParameters: UpdateCompanyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CompanyResponse>> {
    const requestOptions = await this.updateCompanyRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => CompanyResponseFromJSON(jsonValue));
  }

  /**
   * Update a company
   * Update a company
   */
  async updateCompany(
    requestParameters: UpdateCompanyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CompanyResponse> {
    const response = await this.updateCompanyRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
