/* tslint:disable */
/* eslint-disable */
/**
 * Secure Backend Service API
 * Basic secure backend service
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type ErrorMessageBody,
  ErrorMessageBodyFromJSON,
  ErrorMessageBodyToJSON,
} from '../models/ErrorMessageBody';
import {
  type ProfileCreateRequest,
  ProfileCreateRequestFromJSON,
  ProfileCreateRequestToJSON,
} from '../models/ProfileCreateRequest';
import {
  type ProfileResponse,
  ProfileResponseFromJSON,
  ProfileResponseToJSON,
} from '../models/ProfileResponse';
import {
  type ProfileUpdateRequest,
  ProfileUpdateRequestFromJSON,
  ProfileUpdateRequestToJSON,
} from '../models/ProfileUpdateRequest';
import {
  type ProfilesResponse,
  ProfilesResponseFromJSON,
  ProfilesResponseToJSON,
} from '../models/ProfilesResponse';

export interface CreateProfileRequest {
  profileCreateRequest?: ProfileCreateRequest;
}

export interface DeleteProfileRequest {
  id: string;
}

export interface GetProfileRequest {
  id: string;
}

export interface GetProfilesRequest {
  profileType?: GetProfilesProfileTypeEnum;
  page?: number;
  pageSize?: number;
}

export interface UpdateProfileRequest {
  id: string;
  profileUpdateRequest?: ProfileUpdateRequest;
}

/**
 *
 */
export class ProfileApi extends runtime.BaseAPI {
  /**
   * Creates request options for createProfile without sending the request
   */
  async createProfileRequestOpts(
    requestParameters: CreateProfileRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken('oauth', [
        'profile_write',
      ]);
    }

    let urlPath = `/api/v1/profiles`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: ProfileCreateRequestToJSON(requestParameters['profileCreateRequest']),
    };
  }

  /**
   * Create a profile
   * Create a profile
   */
  async createProfileRaw(
    requestParameters: CreateProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProfileResponse>> {
    const requestOptions = await this.createProfileRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProfileResponseFromJSON(jsonValue));
  }

  /**
   * Create a profile
   * Create a profile
   */
  async createProfile(
    requestParameters: CreateProfileRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProfileResponse> {
    const response = await this.createProfileRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for deleteProfile without sending the request
   */
  async deleteProfileRequestOpts(
    requestParameters: DeleteProfileRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteProfile().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken('oauth', [
        'profile_write',
      ]);
    }

    let urlPath = `/api/v1/profiles/{id}`;
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Delete a profile
   * Delete a profile
   */
  async deleteProfileRaw(
    requestParameters: DeleteProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteProfileRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a profile
   * Delete a profile
   */
  async deleteProfile(
    requestParameters: DeleteProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteProfileRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for getProfile without sending the request
   */
  async getProfileRequestOpts(requestParameters: GetProfileRequest): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getProfile().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken('oauth', [
        'profile_read',
      ]);
    }

    let urlPath = `/api/v1/profiles/{id}`;
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Retrieve a single profile by id
   * Retrieve a profile by id information
   */
  async getProfileRaw(
    requestParameters: GetProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProfileResponse>> {
    const requestOptions = await this.getProfileRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProfileResponseFromJSON(jsonValue));
  }

  /**
   * Retrieve a single profile by id
   * Retrieve a profile by id information
   */
  async getProfile(
    requestParameters: GetProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProfileResponse> {
    const response = await this.getProfileRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getProfiles without sending the request
   */
  async getProfilesRequestOpts(
    requestParameters: GetProfilesRequest,
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters['profileType'] != null) {
      queryParameters['profileType'] = requestParameters['profileType'];
    }

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['pageSize'] = requestParameters['pageSize'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken('oauth', [
        'profile_read',
      ]);
    }

    let urlPath = `/api/v1/profiles`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Retrieve a profile\'s information by providing one of the following query parameters: `jobs`, `provinceId`, `cantonId`, `districtId`
   * Retrieve profiles information
   */
  async getProfilesRaw(
    requestParameters: GetProfilesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProfilesResponse>> {
    const requestOptions = await this.getProfilesRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProfilesResponseFromJSON(jsonValue),
    );
  }

  /**
   * Retrieve a profile\'s information by providing one of the following query parameters: `jobs`, `provinceId`, `cantonId`, `districtId`
   * Retrieve profiles information
   */
  async getProfiles(
    requestParameters: GetProfilesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProfilesResponse> {
    const response = await this.getProfilesRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateProfile without sending the request
   */
  async updateProfileRequestOpts(
    requestParameters: UpdateProfileRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updateProfile().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken('oauth', [
        'profile_write',
      ]);
    }

    let urlPath = `/api/v1/profiles/{id}`;
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: ProfileUpdateRequestToJSON(requestParameters['profileUpdateRequest']),
    };
  }

  /**
   * Update a profile
   * Update a profile
   */
  async updateProfileRaw(
    requestParameters: UpdateProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProfileResponse>> {
    const requestOptions = await this.updateProfileRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ProfileResponseFromJSON(jsonValue));
  }

  /**
   * Update a profile
   * Update a profile
   */
  async updateProfile(
    requestParameters: UpdateProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProfileResponse> {
    const response = await this.updateProfileRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const GetProfilesProfileTypeEnum = {
  Employer: 'EMPLOYER',
  Employee: 'EMPLOYEE',
} as const;
export type GetProfilesProfileTypeEnum =
  (typeof GetProfilesProfileTypeEnum)[keyof typeof GetProfilesProfileTypeEnum];
