services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    platform: linux/arm64
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/demo-realm.json:/opt/keycloak/data/import/demo-realm.json
